ZENLESS_DATA = "https://git.mero.moe/dimbreath/ZenlessData/raw/branch/master"

EQUIPMENT_LEVEL = f"{ZENLESS_DATA}/FileCfg/EquipmentLevelTemplateTb.json"
EQUIPMENT = f"{ZENLESS_DATA}/FileCfg/EquipmentTemplateTb.json"
WEAPON_LEVEL = f"{ZENLESS_DATA}/FileCfg/WeaponLevelTemplateTb.json"
WEAPON_STAR = f"{ZENLESS_DATA}/FileCfg/WeaponStarTemplateTb.json"
BUDDY_STAR = f"{ZENLESS_DATA}/FileCfg/BuddyStarTemplateTb.json"
BUDDY_LEVEL_ADVANCE = f"{ZENLESS_DATA}/FileCfg/BuddyLevelAdvanceTemplateTb.json"
AVATAR_SKILL_LEVEL = f"{ZENLESS_DATA}/FileCfg/AvatarSkillLevelTemplateTb.json"
TITLE_CONFIG = f"{ZENLESS_DATA}/FileCfg/TitleConfigTemplateTb.json"
