name: Update Data

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 every day
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/main.yml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync

      - name: Cook
        run: uv run python cook_jsons.py --gi --hsr --zzz

      - name: Commit changes
        run: |
          git add data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: Update data" && git push)
