name: Update Data

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 every day
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 # Use the required Python version

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Cook
        run: poetry run python cook_jsons.py

      - name: Commit changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update data" && git push)
